extend type MenuItem {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "MenuItem", purpose: IMPLICIT_KEY_FIELD)
}
extend type Reservation {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Reservation", purpose: IMPLICIT_KEY_FIELD)
  """
  ✨ Implicit foreign key field based on `Reservation`.`table`. It must match the value of `Table`.`id`. See `@ref` for how to customize it.
  """
  tableId: UUID @fdc_generated(from: "Reservation.table", purpose: IMPLICIT_REF_FIELD)
  """
  ✨ Implicit foreign key field based on `Reservation`.`user`. It must match the value of `User`.`id`. See `@ref` for how to customize it.
  """
  userId: UUID! @fdc_generated(from: "Reservation.user", purpose: IMPLICIT_REF_FIELD)
}
extend type RestaurantInfo {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "RestaurantInfo", purpose: IMPLICIT_KEY_FIELD)
}
extend type Table {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "Table", purpose: IMPLICIT_KEY_FIELD)
}
extend type User {
  """
  ✨ Implicit primary key field. It's a UUID column default to a generated new value. See `@table` for how to customize it.
  """
  id: UUID! @default(expr: "uuidV4()") @fdc_generated(from: "User", purpose: IMPLICIT_KEY_FIELD)
}
