extend type Mutation {
  """
  ✨ Insert a single `MenuItem` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  menuItem_insert(
    """
    Data object to insert into the table.
    """
    data: MenuItem_Data!
  ): MenuItem_KeyOutput! @fdc_generated(from: "MenuItem", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Reservation` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reservation_insert(
    """
    Data object to insert into the table.
    """
    data: Reservation_Data!
  ): Reservation_KeyOutput! @fdc_generated(from: "Reservation", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `RestaurantInfo` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  restaurantInfo_insert(
    """
    Data object to insert into the table.
    """
    data: RestaurantInfo_Data!
  ): RestaurantInfo_KeyOutput! @fdc_generated(from: "RestaurantInfo", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `Table` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  table_insert(
    """
    Data object to insert into the table.
    """
    data: Table_Data!
  ): Table_KeyOutput! @fdc_generated(from: "Table", purpose: INSERT_SINGLE)
  """
  ✨ Insert a single `User` into the table and return its key. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insert(
    """
    Data object to insert into the table.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: INSERT_SINGLE)
  """
  ✨ Insert `MenuItem` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  menuItem_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [MenuItem_Data!]!
  ): [MenuItem_KeyOutput!]! @fdc_generated(from: "MenuItem", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Reservation` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  reservation_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Reservation_Data!]!
  ): [Reservation_KeyOutput!]! @fdc_generated(from: "Reservation", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `RestaurantInfo` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  restaurantInfo_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [RestaurantInfo_Data!]!
  ): [RestaurantInfo_KeyOutput!]! @fdc_generated(from: "RestaurantInfo", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `Table` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  table_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [Table_Data!]!
  ): [Table_KeyOutput!]! @fdc_generated(from: "Table", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert `User` objects into the table and return their keys. Columns not specified in `data` will receive defaults (e.g. `null`).
  """
  user_insertMany(
    """
    List of data objects to insert into the table.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: INSERT_MULTIPLE)
  """
  ✨ Insert or update a single `MenuItem` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MenuItem`.
  """
  menuItem_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: MenuItem_Data!
  ): MenuItem_KeyOutput! @fdc_generated(from: "MenuItem", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Reservation` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Reservation`.
  """
  reservation_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Reservation_Data!
  ): Reservation_KeyOutput! @fdc_generated(from: "Reservation", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `RestaurantInfo` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RestaurantInfo`.
  """
  restaurantInfo_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: RestaurantInfo_Data!
  ): RestaurantInfo_KeyOutput! @fdc_generated(from: "RestaurantInfo", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `Table` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Table`.
  """
  table_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: Table_Data!
  ): Table_KeyOutput! @fdc_generated(from: "Table", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update a single `User` into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsert(
    """
    Data object to insert or update if it already exists.
    """
    data: User_Data!
  ): User_KeyOutput! @fdc_generated(from: "User", purpose: UPSERT_SINGLE)
  """
  ✨ Insert or update `MenuItem` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `MenuItem`.
  """
  menuItem_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [MenuItem_Data!]!
  ): [MenuItem_KeyOutput!]! @fdc_generated(from: "MenuItem", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Reservation` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Reservation`.
  """
  reservation_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Reservation_Data!]!
  ): [Reservation_KeyOutput!]! @fdc_generated(from: "Reservation", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `RestaurantInfo` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `RestaurantInfo`.
  """
  restaurantInfo_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [RestaurantInfo_Data!]!
  ): [RestaurantInfo_KeyOutput!]! @fdc_generated(from: "RestaurantInfo", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `Table` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `Table`.
  """
  table_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [Table_Data!]!
  ): [Table_KeyOutput!]! @fdc_generated(from: "Table", purpose: UPSERT_MULTIPLE)
  """
  ✨ Insert or update `User` objects into the table, based on the primary key. Returns the key of the newly inserted or existing updated `User`.
  """
  user_upsertMany(
    """
    List of data objects to insert or update if it already exists.
    """
    data: [User_Data!]!
  ): [User_KeyOutput!]! @fdc_generated(from: "User", purpose: UPSERT_MULTIPLE)
  """
  ✨ Update a single `MenuItem` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `MenuItem` or `null` if not found.
  """
  menuItem_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MenuItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MenuItem_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: MenuItem_Data!
  ): MenuItem_KeyOutput @fdc_generated(from: "MenuItem", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Reservation` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Reservation` or `null` if not found.
  """
  reservation_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reservation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reservation_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Reservation_Data!
  ): Reservation_KeyOutput @fdc_generated(from: "Reservation", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `RestaurantInfo` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `RestaurantInfo` or `null` if not found.
  """
  restaurantInfo_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: RestaurantInfo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RestaurantInfo_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: RestaurantInfo_Data!
  ): RestaurantInfo_KeyOutput @fdc_generated(from: "RestaurantInfo", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `Table` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `Table` or `null` if not found.
  """
  table_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Table_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Table_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: Table_Data!
  ): Table_KeyOutput @fdc_generated(from: "Table", purpose: UPDATE_SINGLE)
  """
  ✨ Update a single `User` based on `id`, `key` or `first`, setting columns specified in `data`. Returns the key of the updated `User` or `null` if not found.
  """
  user_update(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow

    """
    Data object containing fields to be updated.
    """
    data: User_Data!
  ): User_KeyOutput @fdc_generated(from: "User", purpose: UPDATE_SINGLE)
  """
  ✨ Update `MenuItem` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  menuItem_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: MenuItem_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: MenuItem_Data!
  ): Int! @fdc_generated(from: "MenuItem", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Reservation` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  reservation_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Reservation_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Reservation_Data!
  ): Int! @fdc_generated(from: "Reservation", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `RestaurantInfo` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  restaurantInfo_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: RestaurantInfo_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: RestaurantInfo_Data!
  ): Int! @fdc_generated(from: "RestaurantInfo", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `Table` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  table_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: Table_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: Table_Data!
  ): Int! @fdc_generated(from: "Table", purpose: UPDATE_MULTIPLE)
  """
  ✨ Update `User` objects matching `where` conditions (or `all`, if true) according to `data`. Returns the number of rows updated.
  """
  user_updateMany(
    """
    Filter condition to specify which rows to update.
    """
    where: User_Filter

    """
    Set to true to update all rows.
    """
    all: Boolean = false

    """
    Data object containing fields to update.
    """
    data: User_Data!
  ): Int! @fdc_generated(from: "User", purpose: UPDATE_MULTIPLE)
  """
  ✨ Delete a single `MenuItem` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  menuItem_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MenuItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MenuItem_FirstRow
  ): MenuItem_KeyOutput @fdc_generated(from: "MenuItem", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Reservation` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  reservation_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reservation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reservation_FirstRow
  ): Reservation_KeyOutput @fdc_generated(from: "Reservation", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `RestaurantInfo` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  restaurantInfo_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: RestaurantInfo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RestaurantInfo_FirstRow
  ): RestaurantInfo_KeyOutput @fdc_generated(from: "RestaurantInfo", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `Table` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  table_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Table_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Table_FirstRow
  ): Table_KeyOutput @fdc_generated(from: "Table", purpose: DELETE_SINGLE)
  """
  ✨ Delete a single `User` based on `id`, `key` or `first` and return its key (or `null` if not found).
  """
  user_delete(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User_KeyOutput @fdc_generated(from: "User", purpose: DELETE_SINGLE)
  """
  ✨ Delete `MenuItem` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  menuItem_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: MenuItem_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "MenuItem", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Reservation` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  reservation_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Reservation_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Reservation", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `RestaurantInfo` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  restaurantInfo_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: RestaurantInfo_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "RestaurantInfo", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `Table` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  table_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: Table_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "Table", purpose: DELETE_MULTIPLE)
  """
  ✨ Delete `User` objects matching `where` conditions (or `all`, if true). Returns the number of rows deleted.
  """
  user_deleteMany(
    """
    Filter condition to specify which rows to delete.
    """
    where: User_Filter

    """
    Set to true to delete all rows.
    """
    all: Boolean = false
  ): Int! @fdc_generated(from: "User", purpose: DELETE_MULTIPLE)
}
