extend type Query {
  """
  ✨ Look up a single `MenuItem` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  menuItem(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MenuItem_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MenuItem_FirstRow
  ): MenuItem @fdc_generated(from: "MenuItem", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Reservation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  reservation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Reservation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Reservation_FirstRow
  ): Reservation @fdc_generated(from: "Reservation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `RestaurantInfo` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  restaurantInfo(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: RestaurantInfo_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: RestaurantInfo_FirstRow
  ): RestaurantInfo @fdc_generated(from: "RestaurantInfo", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Table` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  table(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Table_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Table_FirstRow
  ): Table @fdc_generated(from: "Table", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `MenuItem` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  menuItems(
    """
    Filter condition to narrow down the query results.
    """
    where: MenuItem_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MenuItem_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MenuItem_Having
  ): [MenuItem!]! @fdc_generated(from: "MenuItem", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Reservation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  reservations(
    """
    Filter condition to narrow down the query results.
    """
    where: Reservation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Reservation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Reservation_Having
  ): [Reservation!]! @fdc_generated(from: "Reservation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `RestaurantInfo` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  restaurantInfos(
    """
    Filter condition to narrow down the query results.
    """
    where: RestaurantInfo_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [RestaurantInfo_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: RestaurantInfo_Having
  ): [RestaurantInfo!]! @fdc_generated(from: "RestaurantInfo", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Table` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  tables(
    """
    Filter condition to narrow down the query results.
    """
    where: Table_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Table_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Table_Having
  ): [Table!]! @fdc_generated(from: "Table", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
